### ISSUE TITLE
current.log runs full

### ISSUE THREAD

**Issue by iz3man** [vikt0rm/dbus-goecharger#1]
I got issues some time ago with a 100% full /data mount and a current.log file that was >2gig of size, and therefore not addressable at all from venusos (not deleteable either). I had to reformat the /data partition to get rid of this issue.

This all happened as I didn't check the current.log which runs full and grows with an ever repeating error message.

```
2022-09-22 11:54:05,276 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
2022-09-22 11:54:05,484 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
2022-09-22 11:54:05,753 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
```

Seems it can't read the MCU's temperature. Anyway I can stop the script from doing so (no pyhthon knowledge on my side, and I don't want to crash anything)? NB: For now I just commented the line 189 out (#) and it seems to work.

Thanks

EDIT: I don't know how venusos works, but it seems there is no logrotate or something? Does your script take care of the growing log file??

**Comment by lLarryLaffer** [comment]
no it doesn't.
change line 242 to
RotatingFileHandler('%s/dbus-goecharger.log' % (os.path.dirname(os.path.realpath(__file__))), maxBytes=100000, backupCount=10),
and add line 23
from logging.handlers import RotatingFileHandler
then you have a rotating log

**Comment by kwindrem** [comment]
In Venus OS, each service manages a rotiting log file using multilog. Look at other services to see how this is done.

**Comment by LukasBenner** [comment]
I had the same problem today. This should really be a fatal issue.
Recovering the system really takes some linux knowledge.
